#!/usr/bin/python

import sys, os, spaceimg

#
# Setup working firectory
spcdir = ".spaceimgs"
tspcdir = "~/"+spcdir
os.chdir(os.environ['HOME'])
if not os.path.exists(spcdir):
	try:
		os.makedirs(spcdir)
		os.system('notify-send -t 0 "created '+tspcdir+'"')
	except PermissionError:
		os.system('notify-send -t 0 "could not write to '+tspcdir+'"')
		sys.exit(0)
os.chdir(spcdir)

#
# Get background
def grabbg():
	#
	# Find today's astronomy image
	bg = spaceimg.getbg()
#	os.system('notify-send -t 0 "space images debug:'+bg[0]+','+str(len(bg[1]))+','+bg[2]+','+bg[3]+'"')
	opt = "-fill "
	if bg[2] == "":
		if bg[3] == "":
			os.system('notify-send -t 0 "Could not determine today\'s astronomy image ... is it a video file?"')
			sys.exit(0)
		path = bg[3]
		opt = "-center "
	else:
		path = bg[2]
	#
	# Detemine if we already have today's image
	if os.path.exists("path.txt"):
		cur_path = open("path.txt", "r").read().strip()
		if cur_path == path:
			os.system('hsetroot '+opt+'today.jpg')
			sys.exit(0)
	try:
		with open('path.txt', 'w') as file:
			file.write(path)
			file.close()
	except PermissionError as e:
		os.system('notify-send -t 0 "could not write to '+tspcdir+'/path.txt"')
	#
	# Get background
	if bg[2] == "": #must be a video taken from an iframe (linked)
		os.system('spacevideo.sh "'+path+'"')
	else:
		os.system('wget -q -O today.jpg "'+path+'"') == 0 or os.system('notify-send -t 0 "could not write to '+tspcdir+'/today.jpg"')
		os.system('touch today.jpg')
		# If its a gif, copy it to the movie file (extensions are all wrong but display progs are okay)
		if path[-4:] == ".gif":
			os.system('cp today.jpg today.gif') == 0 \
				or os.system('notify-send -t 0 "could not write to '+tspcdir+'/today.gif"')
		# If its an mp4, copy it to the movie file (extensions are all wrong but display progs are okay)
		if path[-4:] == ".mp4":
			os.system('cp today.jpg today.mp4') == 0 \
				or os.system('notify-send -t 0 "could not write to '+tspcdir+'/today.mp4"')
			# be sure to extract a frame to display as the background
			os.system('spacevideo.sh local')
	#
	# Set background
#	os.system('notify-send -t 0 "running:hsetroot '+opt+'today.jpg"')
	os.system('hsetroot '+opt+'today.jpg')
	# Dump HTML describing image
	note = '<u><b>'+str(bg[0])+'</b></u>\n'
	note += bg[1]
#	note = note.replace("'", "")
	try:
		with open('today.txt', 'w') as file:
			file.write(note)
			file.close()
	except PermissionError as e:
		os.system('notify-send -t 0 "could not write to '+tspcdir+'/today.txt"')

#
## Main
#

if len(sys.argv) == 1:
		grabbg()
else:
	# print image description
	if not os.path.exists("path.txt"):
		grabbg()
	os.system('notify-send -t 0 "`cat today.txt`"')
	if os.path.exists("today.mp4"):
		if( (os.path.getmtime('today.jpg') - os.path.getmtime('today.mp4'))/3600 < 2 ):
			os.system('mplayer today.mp4')
	if os.path.exists("today.gif"):
		if( (os.path.getmtime('today.jpg') - os.path.getmtime('today.gif'))/3600 < 2 ):
			os.system('animate today.gif')

#
